apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: exchange
build:
  artifacts:
    - image: localhost:5000/my-image
      ko:
        env:
          - "GOCACHE=/Users/manjunath/tt/.gocache"
        main: ./cmd/pac-server
deploy:
  kubectl:
    manifests:
      - deploy/deployment.yaml
