apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: exchange
build:
  artifacts:
  - image: my-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
